apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-app
  template:
    metadata:
      labels:
        app: sentiment-app
    spec:
      containers:
      - name: sentiment-container
        image: sentiment:latest # Replace with your Docker image
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-service
spec:
  selector:
    app: sentiment-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
